[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "filelock>=3.19.1",
    "matplotlib>=3.10.5",
    "numpy>=2.3.2",
    "reportlab>=4.4.3",
]
